### ISSUE TITLE
Add Favicon to Main Window

### ISSUE THREAD

**Issue by willtheorangeguy** [Dog-Face-Development/Erin-Hunter-Book-Chooser#5]
Add a favicon to the window, so the program is easier to recognize.

**Comment by bhazero025** [comment]
I made a PR, please add the icon you want me to use it and I can include it in the PR. Right now I just left as favicon.ico

**Comment by bhazero025** [comment]
I made a PR, please add the icon you want me to use it and I can include it in the PR. Right now I just left as favicon.ico

https://github.com/Dog-Face-Development/Erin-Hunter-Book-Chooser/pull/6

**Comment by willtheorangeguy** [comment]
Merged!
